image: mcr.microsoft.com/dotnet/sdk:9.0

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build -c Release

test:
  stage: test
  script:
    - dotnet test -c Release --logger "trx;LogFileName=test_results.trx"
  artifacts:
    when: always
    paths:
      - "**/TestResults/*.trx"   # quote globs to avoid YAML alias parsing

publish:
  stage: publish
  script:
    # Framework-dependent Windows build (small output; requires .NET runtime on the target PC)
    - dotnet publish BouncingBallGame/BouncingBallGame.csproj -c Release -r win-x64 -o publish/win-x64 -p:DebugType=None -p:DebugSymbols=false
    # Zip so reviewers download a single file
    - cd publish && tar -cvf ../game.tar win-x64
  artifacts:
    when: always
    paths:
      - "game.tar"